Added checking the log level
remerge/cue pull request #2
Opened 2018-04-03 16:34 UTC by gburanov

We need to add the function to check the current log type.
That will help us to write uglier, but more efficient code

Some measurements from this PR:
https://github.com/remerge/go-tracker/pull/8

When changing from
```
		log.WithFields(cue.Fields{
			"topic":   topic,
			"message": string(buf),
		}).Debug("sending safe message")
```
to
```
	if log.EnabledFor(cue.DEBUG) {
		log.WithFields(cue.Fields{
			"topic":   topic,
			"message": string(buf),
		}).Debug("sending safe message")
	}
```

Reduces the number of heap allocations from 18489 to 14302

2018-04-03 16:36 UTC, akaspin requested changes

2018-04-03 16:36 UTC, akaspin commented on logger.go
> +	if level > config.threshold {
Maybe just `return level < config.threshold`?

2018-04-03 16:38 UTC, gburanov commented on logger.go
> +	if level > config.threshold {
yes, sure)

2018-04-03 16:42 UTC, gburanov commented on logger.go
> +	if level > config.threshold {
actually level <= config.threshold

2018-04-03 16:46 UTC, akaspin approved these changes
👍

2018-04-03 18:34 UTC, gburanov commented
Alternative implementation https://github.com/remerge/cue/pull/3

2018-04-04 09:54 UTC, dynamix approved these changes
Looks good. I like this more than the `SmartSend` in #3 because it still allows you to use `.WithValue` which doesn't create a cue.Fields if you only have a single k/v pair and formatting of the string with varargs.

Having said that. Why not just a method that returns the log level?

2018-04-04 15:38 UTC, gburanov commented
@dynamix  for me this method will be confusing. For example if it will return Debug, than this does not actually mean that INFO messages are not logged

2018-04-04 15:40 UTC, merged